name: Frontend Deploy
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"
  release:
    types: [published]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        working-directory: ./frontend
        run: npm install
      - name: Generate
        working-directory: ./frontend
        run: npm run generate
        env:
          API_URL: https://api.j8g.com
          IMAGE_SERVING_URL: https://cdn.j8g.com
          VER: ${{ github.ref }}
          SITE_NAME: "j8g Admin"
          SITE_DESCRIPTION: "j8g Admin is a dashboard for administering the j8g API"
          SITE_IMAGE_URL: https://cdn.j8g.com/permanent/android-chrome-512x512.png
          SITE_CONTACT_EMAIL:
          SITE_DISCORD_LINK:
          SITE_GITHUB_REPOSITORY_URL:
          LOGO_HAS_LIGHT_VARIANT:
          DEFAULT_LIGHT_MODE: true
          DEFAULT_GRID_VIEW:
          SOCIAL_LOGIN_ENABLED:
          TEMP_STORAGE_PATH: temp
          STRIPE_PUB_KEY:
      - name: Create SA key
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/gcloud.json
      - name: Deploy Hosting
        run: export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json && cd frontend && npx firebase-tools deploy --only hosting --json
